version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - db_data:/data
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
      - SECRET_KEY=your_secret_key
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  db_data:
  pg_data: